import type { Metadata } from 'next';

import { Roboto } from 'next/font/google';
import '../../sass/App.scss';

const rubik = Roboto({
  subsets: ['cyrillic'],
  variable: '--font-roboto',
  weight: ['400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Кинопосик',
  description: 'Generated by create next app',
};

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={rubik.variable}>
      <body>
        <div className="search">{children}</div>
      </body>
    </html>
  );
}
