import type { Metadata } from 'next';

import '../../sass/App.scss';

export const metadata: Metadata = {
  title: 'Кинопосик',
  description: 'Generated by create next app',
};

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="search">{children}</div>
      </body>
    </html>
  );
}
