import { Header } from '@/shared/components/index';
import type { Metadata } from 'next';

import { Rubik } from 'next/font/google';
import '../App.scss';
import StoreProvider from './StoreProvider';

const rubik = Rubik({
  subsets: ['cyrillic'],
  variable: '--font-rubik',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Кинопосик',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={rubik.variable} lang="en">
      <body>
        <StoreProvider>
          <Header />
          <main className="main">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
